sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mdhananjaya/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mdhananjaya/docker-react npm run test
